# Generated by Django 5.2.17 on 2026-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='event_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='email_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='sms_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='whatsapp_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
