# Generated by Django 5.2.17 on 2026-09-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alert_event_id_notificationlog_email_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='max_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='min_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='trip_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='trip_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='trip_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='trip_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='driver_email_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='driver_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='driver_sms_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='driver_sms_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='driver_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='fleet_email_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='fleet_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='fleet_sms_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='fleet_sms_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='fleet_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='is_silenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='manager_email_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='manager_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='manager_sms_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='manager_sms_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='manager_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='event_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
