#!/usr/bin/env python3
"""
generate_seed.py — Generates a rich fake dataset for the GPS Fleet Tracking System.
Produces: data/seed.sql with all INSERT statements.

Requirements: 15+ drivers, 20 vehicles, months of data.
Run from the project root: python data/generate_seed.py
"""
import random
import math
from datetime import datetime, timedelta, date
from decimal import Decimal

random.seed(42)

# ---- CONFIGURATION ----
NUM_DRIVERS = 17
NUM_VEHICLES = 20
MONTHS_BACK = 6   # Generate 6 months of historical data
TRIPS_PER_DAY_RANGE = (1, 4)
TELEMETRY_POINTS_PER_TRIP = 20

# ---- REFERENCE DATA ----
DRIVER_NAMES = [
    "Rohan Sharma", "Priya Patel", "Amit Kumar", "Sunita Devi", "Rajesh Verma",
    "Kavitha Nair", "Suresh Yadav", "Meena Iyer", "Deepak Joshi", "Anita Singh",
    "Vijay Reddy", "Lakshmi Rao", "Manoj Tiwari", "Geeta Gupta", "Sanjay Mishra",
    "Rekha Saxena", "Ravi Chauhan"
]
VEHICLE_TYPES = ["Truck", "Van", "Car", "Mini Truck", "Pickup", "Bus"]
MAKE_MODELS = ["Tata Ace", "Mahindra Bolero", "Ashok Leyland", "Maruti Eeco", "Toyota Innova",
               "Tata Prima", "Eicher Pro", "Force Traveller", "Bajaj Maxima", "Piaggio Ape"]
FUEL_TYPES = ["Diesel", "Petrol", "CNG"]
LOCATIONS = [
    "Mumbai-Pune Expressway", "NH-48 Delhi-Mumbai", "Outer Ring Road Bangalore",
    "NH-8 Jaipur Road", "Eastern Express Highway", "Bandra-Worli Sea Link",
    "Yamuna Expressway Agra", "Nashik Highway", "Thane Creek Bridge", "Sion-Panvel Highway",
    "NH-44 Hyderabad-Nagpur", "Gurgaon-Faridabad Road", "Noida Expressway",
    "Chennai OMR", "Pune Bypass", "Ahmedabad-Vadodara Expressway",
    "Kolkata Bypass", "Delhi-Meerut Expressway", "Bengaluru-Mysore Highway", "Kochi Bypass"
]
ALERT_TYPES = [
    ("Overspeed Alert", "CRITICAL"),
    ("Harsh Braking Alert", "WARNING"),
    ("GPS Disconnect Alert", "CRITICAL"),
    ("Night Driving Alert", "WARNING"),
    ("Ignition Alert", "INFO"),
]

out = []

def sql(s): out.append(s)

def q(v):
    if v is None: return "NULL"
    if isinstance(v, bool): return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float, Decimal)): return str(v)
    return "'" + str(v).replace("'", "''") + "'"

# ---- HEADER ----
sql("-- seed.sql: Auto-generated fake dataset for GPS Fleet Tracking System")
sql("-- Generated by data/generate_seed.py")
sql("-- 17 drivers, 20 vehicles, 6 months of data")
sql("")
sql("BEGIN;")
sql("")

# ---- DRIVERS ----
sql("-- ============================================================")
sql("-- DRIVERS")
sql("-- ============================================================")
drivers = []
phone_base = 9876540000
license_base = "MH2024DL"
joined_start = date(2020, 1, 1)

for i, name in enumerate(DRIVER_NAMES[:NUM_DRIVERS]):
    code = f"DRV{i+1:03d}"
    phone = f"9{phone_base + i}"
    license_num = f"{license_base}{i+1:04d}"
    joined_on = joined_start + timedelta(days=random.randint(0, 1000))
    d = {"id": i+1, "code": code, "name": name, "phone": phone,
         "license_number": license_num, "joined_on": joined_on}
    drivers.append(d)
    sql(f"INSERT INTO drivers (id, code, name, phone, license_number, joined_on, active, created_at) VALUES "
        f"({q(d['id'])}, {q(code)}, {q(name)}, {q(phone)}, {q(license_num)}, {q(str(joined_on))}, TRUE, NOW());")

sql(f"SELECT setval('drivers_id_seq', {NUM_DRIVERS});")
sql("")

# ---- VEHICLES ----
sql("-- ============================================================")
sql("-- VEHICLES")
sql("-- ============================================================")
vehicles = []
for i in range(NUM_VEHICLES):
    code = f"VH{i+1:03d}"
    letters = "ABCDEFGHJKLMNPQRSTUVWXYZ"
    reg = f"MH{random.randint(1,50):02d}{random.choice(letters)}{random.choice(letters)}{random.randint(1000,9999)}"
    vtype = random.choice(VEHICLE_TYPES)
    make = random.choice(MAKE_MODELS)
    fuel = random.choice(FUEL_TYPES)
    driver = random.choice(drivers)
    tank = round(random.uniform(40, 100), 1)
    mileage = round(random.uniform(10, 20), 1)
    odometer = round(random.uniform(20000, 150000), 1)
    imei = f"86{random.randint(10**13, 10**14-1)}"[:15]
    v = {"id": i+1, "code": code, "imei": imei, "reg": reg, "type": vtype,
         "make": make, "fuel": fuel, "driver_id": driver["id"],
         "tank": tank, "mileage": mileage, "odometer": odometer}
    vehicles.append(v)
    sql(f"INSERT INTO vehicles (id, code, imei, registration_number, vehicle_type, make_model, fuel_type, "
        f"tank_capacity_litres, rated_mileage_kmpl, odometer_km, driver_id, active, created_at) VALUES "
        f"({q(v['id'])}, {q(code)}, {q(imei)}, {q(reg)}, {q(vtype)}, {q(make)}, {q(fuel)}, "
        f"{tank}, {mileage}, {odometer}, {q(driver['id'])}, TRUE, NOW());")

sql(f"SELECT setval('vehicles_id_seq', {NUM_VEHICLES});")
sql("")

# ---- TRIPS, ALERTS, DRIVER_DAILY_STATS ----
sql("-- ============================================================")
sql("-- TRIPS (Entry/Exit records)")
sql("-- ============================================================")

start_date = date.today() - timedelta(days=MONTHS_BACK * 30)
end_date = date.today()
trip_id = 0
alert_id = 0
stats_id = 0
stats_map = {}  # (driver_id, date) -> stats dict

current_date = start_date
while current_date <= end_date:
    for vehicle in vehicles:
        driver = next((d for d in drivers if d["id"] == vehicle["driver_id"]), drivers[0])
        n_trips = random.randint(*TRIPS_PER_DAY_RANGE)
        hour = random.randint(6, 10)
        for _ in range(n_trips):
            trip_id += 1
            start_hour = hour
            start_min = random.randint(0, 59)
            duration_min = random.randint(15, 180)
            start_dt = datetime(current_date.year, current_date.month, current_date.day, start_hour, start_min)
            end_dt = start_dt + timedelta(minutes=duration_min)
            if end_dt.date() > current_date: end_dt = datetime(current_date.year, current_date.month, current_date.day, 23, 59)
            hour = min(end_dt.hour + random.randint(0, 2), 22)
            loc = random.choice(LOCATIONS)
            dist = round(random.uniform(5, 200), 2)
            max_spd = round(random.uniform(50, 130), 1)
            min_spd = round(random.uniform(0, 30), 1)
            avg_spd = round(random.uniform(min_spd, max_spd), 1)
            lat_s = round(random.uniform(18.5, 19.2), 7)
            lon_s = round(random.uniform(72.8, 73.2), 7)
            lat_e = lat_s + round(random.uniform(-0.3, 0.3), 7)
            lon_e = lon_s + round(random.uniform(-0.3, 0.3), 7)
            is_night = (start_hour >= 22 or start_hour < 5)
            night_sec = duration_min * 60 if is_night else 0
            overspd_evts = random.randint(0, 3) if max_spd > 80 else 0
            harsh_brk = random.randint(0, 2)
            harsh_acc = random.randint(0, 2)
            alert_cnt = overspd_evts + harsh_brk
            moving_sec = int(duration_min * 60 * 0.85)
            idle_sec = duration_min * 60 - moving_sec

            sql(f"INSERT INTO trips (id, vehicle_id, driver_id, start_time, end_time, status, "
                f"start_latitude, start_longitude, end_latitude, end_longitude, distance_km, duration_seconds, "
                f"moving_seconds, idle_seconds, max_speed_kmph, min_speed_kmph, average_speed_kmph, "
                f"overspeed_events, harsh_braking_events, harsh_acceleration_events, night_driving_seconds, "
                f"alert_count, primary_road, created_at) VALUES "
                f"({trip_id}, {vehicle['id']}, {driver['id']}, "
                f"{q(str(start_dt))}, {q(str(end_dt))}, 'COMPLETED', "
                f"{lat_s}, {lon_s}, {lat_e}, {lon_e}, {dist}, {duration_min*60}, "
                f"{moving_sec}, {idle_sec}, {max_spd}, {min_spd}, {avg_spd}, "
                f"{overspd_evts}, {harsh_brk}, {harsh_acc}, {night_sec}, {alert_cnt}, {q(loc)}, NOW());")

            # Alerts for this trip
            trip_alert_types = []
            if overspd_evts > 0: trip_alert_types.append(("Overspeed Alert", "CRITICAL"))
            if harsh_brk > 0: trip_alert_types.append(("Harsh Braking Alert", "WARNING"))
            if is_night: trip_alert_types.append(("Night Driving Alert", "WARNING"))
            if random.random() < 0.03: trip_alert_types.append(("GPS Disconnect Alert", "CRITICAL"))
            if random.random() < 0.05: trip_alert_types.append(("Ignition Alert", "INFO"))

            for (atype, severity) in trip_alert_types:
                alert_id += 1
                at = start_dt + timedelta(minutes=random.randint(2, max(3, duration_min-1)))
                ref = f"SEED_{vehicle['code']}_{trip_id}_{atype.replace(' ','')[:12]}_{alert_id}"
                spd = max_spd if "Overspeed" in atype else round(random.uniform(30, max_spd), 1)
                spd_limit = 80.0
                lat_a = round(lat_s + random.uniform(-0.05, 0.05), 7)
                lon_a = round(lon_s + random.uniform(-0.05, 0.05), 7)
                sql(f"INSERT INTO alerts (id, reference, alert_type, severity, vehicle_id, driver_id, trip_id, "
                    f"occurred_at, latitude, longitude, speed_kmph, speed_limit_kmph, road_name, "
                    f"trip_start_time, trip_end_time, trip_distance_km, trip_duration_min, min_speed_kmph, max_speed_kmph, "
                    f"status, delivery_status, email_sent, sms_sent, created_at) VALUES "
                    f"({alert_id}, {q(ref)}, {q(atype)}, {q(severity)}, {vehicle['id']}, {driver['id']}, {trip_id}, "
                    f"{q(str(at))}, {lat_a}, {lon_a}, {spd}, {spd_limit}, {q(loc)}, "
                    f"{q(str(start_dt))}, {q(str(end_dt))}, {dist}, {duration_min}, {min_spd}, {max_spd}, "
                    f"'HISTORICAL', 'SILENCED', FALSE, FALSE, NOW());")

            # Accumulate daily stats
            key = (driver["id"], current_date)
            if key not in stats_map:
                stats_map[key] = {"driver_id": driver["id"], "stat_date": current_date,
                    "distance_km": 0, "driving_seconds": 0, "idle_seconds": 0, "trip_count": 0,
                    "max_speed_kmph": 0, "avg_speeds": [], "overspeed_events": 0,
                    "harsh_braking_events": 0, "harsh_acceleration_events": 0,
                    "night_driving_seconds": 0, "fatigue_events": 0}
            s = stats_map[key]
            s["distance_km"] += dist
            s["driving_seconds"] += moving_sec
            s["idle_seconds"] += idle_sec
            s["trip_count"] += 1
            s["max_speed_kmph"] = max(s["max_speed_kmph"], max_spd)
            s["avg_speeds"].append(avg_spd)
            s["overspeed_events"] += overspd_evts
            s["harsh_braking_events"] += harsh_brk
            s["harsh_acceleration_events"] += harsh_acc
            s["night_driving_seconds"] += night_sec
    current_date += timedelta(days=1)

sql(f"SELECT setval('trips_id_seq', {trip_id});")
sql(f"SELECT setval('alerts_id_seq', {alert_id});")
sql("")

# ---- DRIVER DAILY STATS ----
sql("-- ============================================================")
sql("-- DRIVER DAILY STATS")
sql("-- ============================================================")
sid = 0
for (driver_id, stat_date), s in stats_map.items():
    sid += 1
    avg_spd = round(sum(s["avg_speeds"]) / len(s["avg_speeds"]), 2) if s["avg_speeds"] else 0
    overspd = s["overspeed_events"]
    harsh_brk = s["harsh_braking_events"]
    harsh_acc = s["harsh_acceleration_events"]
    night_hrs = s["night_driving_seconds"] / 3600
    fatigue = s["fatigue_events"]
    clean_trips = max(0, s["trip_count"] - (1 if overspd > 0 or harsh_brk > 0 else 0))
    score = max(0, min(100, 100 - overspd*5 - harsh_brk*4 - harsh_acc*4 - night_hrs*3 - fatigue*8 + clean_trips))
    score = round(score, 2)
    sql(f"INSERT INTO driver_daily_stats (id, driver_id, stat_date, distance_km, driving_seconds, idle_seconds, "
        f"trip_count, max_speed_kmph, average_speed_kmph, overspeed_events, harsh_braking_events, "
        f"harsh_acceleration_events, night_driving_seconds, fatigue_events, safety_score) VALUES "
        f"({sid}, {driver_id}, {q(str(stat_date))}, {round(s['distance_km'],3)}, {s['driving_seconds']}, "
        f"{s['idle_seconds']}, {s['trip_count']}, {round(s['max_speed_kmph'],2)}, {avg_spd}, "
        f"{overspd}, {harsh_brk}, {harsh_acc}, {s['night_driving_seconds']}, {fatigue}, {score});")

sql(f"SELECT setval('driver_daily_stats_id_seq', {sid});")
sql("")

# ---- MAINTENANCE RECORDS ----
sql("-- ============================================================")
sql("-- MAINTENANCE RECORDS")
sql("-- ============================================================")
service_types = ["OIL_CHANGE", "TIRE_ROTATION", "BRAKE_SERVICE", "ENGINE_TUNE", "FILTER_CHANGE", "BATTERY_CHECK", "AC_SERVICE"]
mid = 0
for v in vehicles:
    for i in range(random.randint(2, 5)):
        mid += 1
        sdate = date.today() - timedelta(days=random.randint(30, 180))
        stype = random.choice(service_types)
        cost = round(random.uniform(500, 15000), 2)
        odo = round(random.uniform(20000, 150000), 1)
        next_due = sdate + timedelta(days=random.randint(60, 180))
        sql(f"INSERT INTO maintenance_records (id, vehicle_id, service_type, serviced_on, odometer_km, cost_inr, "
            f"next_service_due_on, data_source, created_at) VALUES "
            f"({mid}, {v['id']}, {q(stype)}, {q(str(sdate))}, {odo}, {cost}, {q(str(next_due))}, 'CSV_IMPORT', NOW());")

sql(f"SELECT setval('maintenance_records_id_seq', {mid});")
sql("")

# ---- COST RECORDS ----
sql("-- ============================================================")
sql("-- COST RECORDS (FUEL)")
sql("-- ============================================================")
cid = 0
for v in vehicles:
    for i in range(random.randint(10, 25)):
        cid += 1
        cdate = date.today() - timedelta(days=random.randint(1, 180))
        qty = round(random.uniform(20, 80), 2)
        unit_price = round(random.uniform(90, 105), 2)
        amount = round(qty * unit_price, 2)
        odo = round(random.uniform(20000, 150000), 1)
        sql(f"INSERT INTO cost_records (id, vehicle_id, cost_type, amount_inr, quantity, unit_price_inr, "
            f"odometer_km, incurred_on, data_source, created_at) VALUES "
            f"({cid}, {v['id']}, 'FUEL', {amount}, {qty}, {unit_price}, {odo}, {q(str(cdate))}, 'CSV_IMPORT', NOW());")

sql(f"SELECT setval('cost_records_id_seq', {cid});")
sql("")
sql("COMMIT;")
sql("")
sql(f"-- Summary: {NUM_DRIVERS} drivers, {NUM_VEHICLES} vehicles, {trip_id} trips, {alert_id} alerts, {sid} daily stats rows")

output = "\n".join(out)
with open("data/seed.sql", "w", encoding="utf-8") as f:
    f.write(output)

print(f"Generated data/seed.sql")
print(f"  Drivers:        {NUM_DRIVERS}")
print(f"  Vehicles:       {NUM_VEHICLES}")
print(f"  Trips:          {trip_id}")
print(f"  Alerts:         {alert_id}")
print(f"  Daily Stats:    {sid}")
print(f"  Maintenance:    {mid}")
print(f"  Cost Records:   {cid}")
